# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lattice.proto_gen import lattice_pb2 as lattice__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lattice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LatticeSchedulerStub(object):
    """── Services ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/lattice.LatticeScheduler/Submit',
                request_serializer=lattice__pb2.SubmitRequest.SerializeToString,
                response_deserializer=lattice__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/lattice.LatticeScheduler/Cancel',
                request_serializer=lattice__pb2.CancelRequest.SerializeToString,
                response_deserializer=lattice__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/lattice.LatticeScheduler/Status',
                request_serializer=lattice__pb2.StatusRequest.SerializeToString,
                response_deserializer=lattice__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/lattice.LatticeScheduler/List',
                request_serializer=lattice__pb2.ListRequest.SerializeToString,
                response_deserializer=lattice__pb2.ListResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/lattice.LatticeScheduler/StreamEvents',
                request_serializer=lattice__pb2.StreamRequest.SerializeToString,
                response_deserializer=lattice__pb2.JobEvent.FromString,
                _registered_method=True)
        self.ClusterStats = channel.unary_unary(
                '/lattice.LatticeScheduler/ClusterStats',
                request_serializer=lattice__pb2.ClusterRequest.SerializeToString,
                response_deserializer=lattice__pb2.ClusterStatus.FromString,
                _registered_method=True)


class LatticeSchedulerServicer(object):
    """── Services ──────────────────────────────────────────────────────────────────

    """

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClusterStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LatticeSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=lattice__pb2.SubmitRequest.FromString,
                    response_serializer=lattice__pb2.SubmitResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=lattice__pb2.CancelRequest.FromString,
                    response_serializer=lattice__pb2.CancelResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=lattice__pb2.StatusRequest.FromString,
                    response_serializer=lattice__pb2.StatusResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=lattice__pb2.ListRequest.FromString,
                    response_serializer=lattice__pb2.ListResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=lattice__pb2.StreamRequest.FromString,
                    response_serializer=lattice__pb2.JobEvent.SerializeToString,
            ),
            'ClusterStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusterStats,
                    request_deserializer=lattice__pb2.ClusterRequest.FromString,
                    response_serializer=lattice__pb2.ClusterStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lattice.LatticeScheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lattice.LatticeScheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LatticeScheduler(object):
    """── Services ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lattice.LatticeScheduler/Submit',
            lattice__pb2.SubmitRequest.SerializeToString,
            lattice__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lattice.LatticeScheduler/Cancel',
            lattice__pb2.CancelRequest.SerializeToString,
            lattice__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lattice.LatticeScheduler/Status',
            lattice__pb2.StatusRequest.SerializeToString,
            lattice__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lattice.LatticeScheduler/List',
            lattice__pb2.ListRequest.SerializeToString,
            lattice__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lattice.LatticeScheduler/StreamEvents',
            lattice__pb2.StreamRequest.SerializeToString,
            lattice__pb2.JobEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClusterStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lattice.LatticeScheduler/ClusterStats',
            lattice__pb2.ClusterRequest.SerializeToString,
            lattice__pb2.ClusterStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/lattice.WorkerAgent/Heartbeat',
                request_serializer=lattice__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=lattice__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Checkpoint = channel.unary_unary(
                '/lattice.WorkerAgent/Checkpoint',
                request_serializer=lattice__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=lattice__pb2.CheckpointResponse.FromString,
                _registered_method=True)


class WorkerAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=lattice__pb2.HeartbeatRequest.FromString,
                    response_serializer=lattice__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Checkpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkpoint,
                    request_deserializer=lattice__pb2.CheckpointRequest.FromString,
                    response_serializer=lattice__pb2.CheckpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lattice.WorkerAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lattice.WorkerAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lattice.WorkerAgent/Heartbeat',
            lattice__pb2.HeartbeatRequest.SerializeToString,
            lattice__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lattice.WorkerAgent/Checkpoint',
            lattice__pb2.CheckpointRequest.SerializeToString,
            lattice__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
